### ISSUE TITLE
Aplica una "API" oculta "oficial" para consultar el saldo de la tarjeta bip?

### ISSUE THREAD

**Issue by lgaticaq** [juanbrujo/listado-apis-publicas-en-chile#11]
Al hacer un POST a esta url `http://www.metrosantiago.cl/contents/guia-viajero/includes/consultarTarjeta/numero-bip` te entrega un json con el saldo y fecha de la tarjeta.

Es lo mas oficial que he encontrado para la tarjeta bip.

**Comment by gaulatti** [comment]
Debería... :+1:

**Comment by juanbrujo** [comment]
yo tengo este para BIP http://www.psep.cl/api/Bip.php?&numberBip=666

**Comment by lgaticaq** [comment]
Basicamente tienen la misma info, solo que ese recurso obtiene la info desde aca (al parecer) https://github.com/Psep/apis-servicios/blob/master/services/Bip.php#L56

**Comment by juanbrujo** [comment]
horriblemente feo, cual agregamos?

**Comment by lgaticaq** [comment]
Yo voto por consultar a una fuente oficial siempre si es que la hay, y en este caso lo mas oficial que hay es metrosantiago

**Comment by juanbrujo** [comment]
concuerdo. quiero hacer esto crecer y consilidarse: un dominio propio y q vaya mejorandose con el tiempo. Pregunta: seria bueno separar los tipos de servicios, por ejemplo: REST, RSS, POST ....?

**Comment by lgaticaq** [comment]
No creo que sea necesario separar por tipo, quizas solo basta con indicar como consultar el servicio. Por lo general la gente busca por el recurso (bip, farmacias, etc) en vez de por tipo. Cuando crezca apaño con una CLI para consultarla.

**Comment by juanbrujo** [comment]
bien, si quieres agregar la de BIP @lgaticaq bienvenido será por ahora.

**Comment by juanbrujo** [comment]
@lgaticaq 👀

**Comment by lgaticaq** [comment]
Los :ql: quitaron el endpoint. Ahora el oficial es de http://pocae.tstgo.cl/PortalCAE-WAR-MODULE/. Tengo una librería que hace scrapping, así que mejor voy a levantar una api simple que haga la pega más simple. Si quieres me mandas un PR cuando este lista para darle una manito de gato porfa.

**Comment by lgaticaq** [comment]
Lib actualizada https://www.npmjs.com/package/bip. Queda pendiente hacer el microservicio para hacer consultas por GET y obtener un json

**Comment by juanbrujo** [comment]
ok conversemos esto mañana en la beerjs para apoyarte. gracias.

**Comment by csalinastv** [comment]
Los datos tienen un día de diferencia, no sirve de mucho, ya que no están actualizados :(

**Comment by Marmos343** [comment]
Alguien con una api actualizada para ver el saldo de la bip??

**Comment by lgaticaq** [comment]
Tengo esta lib https://www.npmjs.com/package/bip que usa scrapping de la pagina http://www.tarjetabip.cl/

**Comment by juanbrujo** [comment]
agregado la lib.

**Comment by jousel84** [comment]
Buenas!! Funciona esto en 2023?

**Comment by lgaticaq** [comment]
No creo, la lib no ha sido actualizada durante mucho tiempo

**Comment by LiinooRF** [comment]
¡Hola! Disculpa que te moleste, no hay liberia que funcione?, es que necesito conseguir una API, para un proyecto en el liceo :C

**Comment by dannlebeau** [comment]
algo disponible a la fecha?

**Comment by samuros** [comment]
Permiso vengo a dejar esto por acá:

https://github.com/sRosinsky/saldo-bip-api

**Comment by dannlebeau** [comment]
> Permiso vengo a dejar esto por acá:
> 
> https://github.com/sRosinsky/saldo-bip-api

funciona??

**Comment by psazop** [comment]
Acabo de probar y sí funciona:

**Comment by dannlebeau** [comment]
> Acabo de probar y sí funciona:

yo tambien probe, igual me pase que tengo un desfase de 3 dias, me dice que el último uso fue el 19/05 y hoy (22/05) la acabo de usar pero aun no sale reflejado; la idea es al menos que yo busco para hacerla funcional es que se actualice cada 6 horas; porque la pagina de consultar el saldo oficial no me gusta por el desfase y hace que no sea ni funcional, ni practico

**Comment by samuros** [comment]
ya es tema de pocae.tstgo.cl, si alguien tiene otra fuente donde aparezca el saldo actualizado me la puede pasar?

**Comment by LiinooRF** [comment]
En 

https://www.metro.cl/el-viaje/carga-bip

Y también en la website de red.cl 

Ahí te aparece el saldo más actual

**Comment by dannlebeau** [comment]
es lo mismo, presenta el desfase, creo que viene de los servidores, pero por mucho que explore los metadatos de pocae no puedo encontrar nada :(
