### ISSUE TITLE
Cambio de nombre de este repositorio

### ISSUE THREAD

**Issue by juanbrujo** [juanbrujo/listado-apis-publicas-en-chile#13]
Creo que el nombre que tiene ahora no refleja el real objetivo de este proyecto: recopilar fuentes de datos abiertas (y privados o de pago, por que no) que provengan de fuentes nacionales. Me gustaría cambiarlo, se aceptan propuestas como:
- Listado API en / de Chile (creo que para SEO es bueno que tenga el nombre _Chile_)
- Directorio de API's Nacionales
- ?

**Comment by jlizanab** [comment]
1.- chile_apis
2.- chile_open_apis

**Comment by eseceve** [comment]
awesome-chile-opensource-api (?)

**Comment by gaulatti** [comment]
chile-apis

**Comment by ginirsss** [comment]
recipes-chile-api

**Comment by mraddatz** [comment]
Propongo cerrar la Issue siesque listado-apis-publicas-en-chile es el nombre definitivo

**Comment by fskarmeta** [comment]
si, ya pego con todo este nombre
