### ISSUE TITLE
mindicador.cl no es opensource

### ISSUE THREAD

**Issue by punchi** [juanbrujo/listado-apis-publicas-en-chile#14]
eso

**Comment by juanbrujo** [comment]
lo dicen en su propia web ¯_(ツ)_/¯

![screen shot 2016-02-04 at 15 10 04](https://cloud.githubusercontent.com/assets/362186/12824740/77837036-cb51-11e5-8308-2e5bbf81f709.png)

**Comment by punchi** [comment]
...y si dice "es un servicio de Dios", ¿van a crear una rama religiosa? @_@ estimados, un software de código abierto tiene liberado el código para libre acceso/modificación, supongo que está de más este link https://es.wikipedia.org/wiki/C%C3%B3digo_abierto me imagino que también la idea es corregir información cuando se puede, saludos!

**Comment by juanbrujo** [comment]
gracias @punchi
