### ISSUE TITLE
API gob datos

### ISSUE THREAD

**Issue by tamycova** [juanbrujo/listado-apis-publicas-en-chile#15]
Hola! Queria saber si sabes de alguna api para http://datos.gob.cl/, o para obtener big data desde el gobierno. Saludos

**Comment by juanbrujo** [comment]
@tamycova lamentablemente no. Sólo pocaza info que se encuentra en [Kit Digital](http://kitdigital.gob.cl/recursos-de-desarrollo/) dan luz de documentacion y en el [repositorio en GitHub del gobierno](https://github.com/e-gob) algunos intentos que tener algo. Pero una pena ver como suben documentos csv, xls, pdf y no llevarlo a una api pública, seria y abierta.

**Comment by juanbrujo** [comment]
Mira @tamycova [Junar](http://es.wiki.junar.com/index.php/Recursos_datos_gob_cl_API) está arriba hace rato y siempre en su v1.0 quizás te ande. Quise usarla para tener datos de sismos recientes y no pude echarlo a andar.
