### ISSUE TITLE
Sismos Chile retorna `403`

### ISSUE THREAD

**Issue by fernandocanizo** [juanbrujo/listado-apis-publicas-en-chile#18]
La página de sismos chile (http://jaimeguaman.opendata.junar.com/developers/) no sirve, devuelve `403`, es decir, sin autorización.

Probé ir al sitio raíz, para ver si había que registrarse o si indicaba como obtener acceso, pero el home también devuelve `403`.

**Comment by quest** [comment]
todavía sigue arrojando 403 :/

**Comment by juanbrujo** [comment]
@jaimeguaman ☝️

**Comment by jaimeguaman** [comment]
murió Junar, liberaré un API con data almacenada desde 2015 aprox, SOON

**Comment by juanbrujo** [comment]
![soon](https://user-images.githubusercontent.com/362186/38281660-207c048e-3782-11e8-8912-35de41e073f1.jpg)

**Comment by CollapsedMetal** [comment]
Pueden usar la mia por mientras

[https://api.gael.cl/general/public/sismos](https://api.gael.cl/general/public/sismos)

**Comment by juanbrujo** [comment]
gracias @CollapsedMetal
