### ISSUE TITLE
API´s /R

### ISSUE THREAD

**Issue by roroba** [juanbrujo/listado-apis-publicas-en-chile#23]
Hola,

Sabes si se puede entrar a Chile atiende con httr/R??
Trate con:

GET ("https://www.chileatiende.gob.cl/api/fichas/", access_token="xxx")

Pero siempre me devuelve error 403:

  Date: 2018-05-04 15:08
  Status: 403
  Content-Type: application/json
  Size: 21 B
{
    "message": ""

**Comment by juanbrujo** [comment]
ni idea nunca he tratado.
