### ISSUE TITLE
API DataChile

### ISSUE THREAD

**Issue by sergiolucero** [juanbrujo/listado-apis-publicas-en-chile#24]
[DataChile](http://datachile.io) fue lanzado hace un tiempo ya y está muy bonito el sitio. Ahora están lanzando una [API](https://es.datachile.io/about/api) y aunque la [interfaz para python](https://github.com/datachile/datachile-python-client/) no está aún OK (no instala via pip), quizás sería hora de agregarla a esta lista?

**Comment by juanbrujo** [comment]
dale nomás, si quieres mandame el PR

**Comment by ghost** [comment]
Colegas, alguno de ustedes tiene conocimiento de la existencia de alguna API para conocer los peajes de Chile? Me serviría mucho la orientación o algún dato!

**Comment by juanbrujo** [comment]
@pauloc1989 hay algunos no-oficiales y no son API Rest, habría que inspeccionar el origen de la informción:

https://ww2.copec.cl/chiletur/planificador
https://www.intervialchile.cl/peajes-y-tarifas/

**Comment by ghost** [comment]
@juanbrujo Agradecido Juan, revise la información de Copec y alimentan su información mediante un JSON, pero al momento de consultarlo desde mi código me lanza un error con autorización (CORS); Intervial lo revisaré. Si te llegas a enterar de algún servicio que pueda utilizar agradecería me lo indicaras. Saludos!

**Comment by ignaciowg93** [comment]
Estimados. Si bien la documentación está arriba, no logro encontrar el endpoint ni la página para consultar los datos de compras Transparentes. Puede ser que haya sido dado de baja el servicio?

**Comment by juanbrujo** [comment]
Estaremos trabajando para usted, todo aporte se sgradece.

**Comment by sergiolucero** [comment]
Gentes, estoy armando un data lake que nos interesa a todos. Como pitonista
me gustaría que fuera tan simple como

*import boto, pandas, requests*

*bucketName = 'chiledata_bucket'*
*datasets = {'gasolinas': 'http://cne.cl/api/datos.csv
<http://cne.cl/api/datos.csv>', '*
*s3 = boto3.client('s3')*
*for outname, url in datasets.items():*
*    Key = down(url)*
*    s3.upload_file(Key,bucketName,outname)*

Y después ejecutar comandos boto3.client('glue') para crear una base
consultable en Kinesis. Voy a crear un github al respecto por ahí pero lo
seguiré conversando por acá.

**Comment by nmatz** [comment]
Estimados, existe alguna api del demre ?

**Comment by juanbrujo** [comment]
@nmatz solo encontre algo aqui https://es.datachile.io/about/data
