### ISSUE TITLE
Referencias para creación de APIS (Chile)

### ISSUE THREAD

**Issue by fmancini** [juanbrujo/listado-apis-publicas-en-chile#3]
Referencias para creación de APIS (Chile)

Estándares de creación de interfaces de programación de aplicaciones (APIs) en el Gobierno de Chile
http://kitdigital.gob.cl/recursos-de-desarrollo/guia-construccion-apis/

**Comment by juanbrujo** [comment]
@fmancini porq esto es un issue?
