### ISSUE TITLE
API de feriados legales no está funcionando

### ISSUE THREAD

**Issue by nikkonv** [juanbrujo/listado-apis-publicas-en-chile#42]
Eso, intente con el año 2021 y no encuentra datos. Estuve probando esta: https://apis.digital.gob.cl/fl/ y creo que funciona bien.

**Comment by quest** [comment]
Ya volví a dejar operativa la API de feriadosapp.com, con algunos cambios pero está al día.

**Comment by juanbrujo** [comment]
also updated link ad201a3737709877389fd858db02d687f618cbd2
