### ISSUE TITLE
Obtener token de API CNE

### ISSUE THREAD

**Issue by Richard6536** [juanbrujo/listado-apis-publicas-en-chile#53]
Donde se obtiene el token?, la documentación no lo menciona y en la página de cne.cl no he encontrado nada.
https://api.cne.cl/apidocs/

**Comment by juanbrujo** [comment]
@lgaticaq sabes como obtener esto? no encontre nada referido, [salvo esta libreria](https://github.com/Drivetech/node-cne).

**Comment by farevalod** [comment]
Esta en package.json:
"token": "6M5jaVAzPS",
