### ISSUE TITLE
Agregar Celuzador

### ISSUE THREAD

**Issue by Theblood** [juanbrujo/listado-apis-publicas-en-chile#58]
Celuzador es capaz de traer el nombre y la foto de perfil de whatsapp como tambien el estado del mismo

dejo un repositorio con codigo en python3 que consume una api:
https://github.com/Theblood/Celuzador

Tambien dejo un sitio que esta abierto a consultas:
https://celuzador.online/

**Comment by juanbrujo** [comment]
pero esto es un proyecto no es una api publica...

**Comment by rodrigozooft** [comment]
Hey buddy,

Rutificador y BIP are dead.

Gracias por mantener updated esto.
