### ISSUE TITLE
API planos.cl caído

### ISSUE THREAD

**Issue by Luckbox314** [juanbrujo/listado-apis-publicas-en-chile#59]
Al parecer API planos.cl ya no se encuentra disponible y el link que está en la lista no funcina.
No estoy seguro pero parece que el sitio se movió a [OpenStreetMap Chile](https://blog.openstreetmap.cl/tag/api/).

Si no se encuentra el link de API planos, debería marcarse como deprecado.

**Comment by Luckbox314** [comment]
@juanbrujo, tú agregaste API planos.cl así que quizá tu puedas ver si es que hay un link válido o es mejor eliminarlo/deprecarlo.

**Comment by Luckbox314** [comment]
Al parecer OpenStreetMap no está relacionado con API planos y tampoco es algo chileno.

**Comment by juanbrujo** [comment]
@Luckbox314 puedes siempre hacer un PR proponiendo eliminarlo
