### ISSUE TITLE
Diferencias entre API's CNE

### ISSUE THREAD

**Issue by juanbrujo** [juanbrujo/listado-apis-publicas-en-chile#9]
@lgaticaq en q es diferente http://datos.energiaabierta.cne.cl/developers y http://api.cne.cl/?

**Comment by lgaticaq** [comment]
Intente probar la api de energía abierta y no logre ver como se hacia así que supuse que eran distintas, a pesar que son de la misma fuente, tu sabes como usar la primera?

**Comment by sergiolucero** [comment]
Bueno, dado que han pasado 2.5 años y la primera URL está muerta, podríamos cerrar este issue?
